/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package io.opentelemetry.gradle.tracing

/**
 * A simple functional test for the 'io.opentelemetry.gradle.tracing.greeting' plugin.
 */
class GradleOtelTracingPluginFunctionalTest {
}
